default_language_version:
    python: python3.8

exclude: '^(.mypy_cache|.github)'

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-executables-have-shebangs
    exclude: ".py"
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
  - id: remove-tabs
    files: ".py"

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.2
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    additional_dependencies: [toml]

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: ''
  hooks:
  - id: mypy
    additional_dependencies:
      - types-requests
      - types-toml
    args:
    - --ignore-missing-imports
    - --follow-imports=skip

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
